### ISSUE TITLE
Scale all your variables by population to avoid confounding issues 

### ISSUE THREAD

**Issue by SJCaldwell** [mackenziedg/UFOTracker#2]
@mackenziedg said he did this

so let's make sure we're doing this the same way pls

Mac if you could drop your method below as a comment before someone assigns this to themselves that'd be perfect.

**Comment by fbchow** [comment]
I tried to normalize sightings per state by population but I got stuck on the part where you tidy the State Population csv.

https://github.com/mackenziedg/UFOTracker/blob/ufo_data_cleaning/src/ufo_cleaning/base_analysis.Rmd

> state_pops$Name <- mapvalues(state_pops$Name, state.name, state.abb)
> state_pops <- state_pops %>%
>     filter(Name %in% state.abb) %>%
>     select(one_of(c("1970", "1980", "1990", "2000", "2010"))) %>%
>     apply(1, mean)

`The following `from` values were not present in `x`: Alabama, Alaska, Arizona, Arkansas, California, Colorado, Connecticut, Delaware, Florida, Georgia, Hawaii, Idaho, Illinois, Indiana, Iowa, Kansas, Kentucky, Louisiana, Maine, Maryland, Massachusetts, Michigan, Minnesota, Mississippi, Missouri, Montana, Nebraska, Nevada, New Hampshire, New Jersey, New Mexico, New York, North Carolina, North Dakota, Ohio, Oklahoma, Oregon, Pennsylvania, Rhode Island, South Carolina, South Dakota, Tennessee, Texas, Utah, Vermont, Virginia, Washington, West Virginia, Wisconsin, Wyoming
argument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NAargument is not numeric or logical: returning NA`

**Comment by fbchow** [comment]
`### Normalize the number of sightings by the population of each state
df$sightings_per_thousand <- (df$sightings / df$pop) * 1000`

**Comment by fbchow** [comment]
# Rationale for normalizing by 100,000 

## THIS IS HOW YOU WILL INTERPRET THE PREDICTOR VARIABLE Y: 
(Total Sightings per state in that year /State population in that year) x 100,000

> Instead of creating a percentage of each value, we used 100,000 to make the numbers in our reports more manageable (as opposed to values like .01%). That means that the numbers shown in the normalized map represent total number of visits per 100,000 people. We chose to multiply by 100,000, since that is the order of magnitude of the lowest state populations—if we used a value above 100,000, the states with the lowest populations would have normalized values larger than the actual amount of sessions.

https://www.digitalgov.gov/2016/03/11/seeing-states-the-right-way-how-to-weigh-data-by-population/

**Comment by fbchow** [comment]
still need to add normalization of number of movies per year from

Shane's commit: https://github.com/mackenziedg/UFOTracker/commit/e0295f46b2d8c9e624a65210d593a44394618ffe

**Comment by fbchow** [comment]
**year**  

**state**

**region**

**sightings_per_100k**  = (sightings in that state per year / state population for that decade) * 100,000

**breweries** = number of breweries in the state that year 	
(Na’s in early years because data only starts after 1984)

**alienmovies_per_year** = alien movies that year / total movies that year

**per_capita_gdp_current** = per capita gdp that year
(no states in this data)

**Urban 	Suburban 	Rural**  = internet access that year
(no states in this data)

**afbase_per_stater_state** = number of air forces per state 
(no years with this data)

**Comment by SJCaldwell** [comment]
thx @mackenziedg
